"""
waf_detector.py — Web Application Firewall Detection
Identifies Cloudflare, ModSecurity, AWS WAF, Akamai, F5, and more.
"""

import requests
from typing import Optional, Dict, List, Tuple
from dataclasses import dataclass, field


@dataclass
class WAFResult:
    detected: bool = False
    name: str = "None"
    confidence: int = 0          # 0–100
    indicators: List[str] = field(default_factory=list)
    recommendation: str = ""


class WAFDetector:
    """Passive + active WAF fingerprinting."""

    # (WAF name, [(header_key, value_substring), ...], [body_substring, ...])
    SIGNATURES: List[Tuple[str, List[Tuple[str, str]], List[str]]] = [
        (
            "Cloudflare",
            [("server", "cloudflare"), ("cf-ray", "")],
            ["cloudflare", "cf-ray", "Error 1020"],
        ),
        (
            "ModSecurity",
            [("server", "mod_security"), ("x-sucuri-id", "")],
            ["ModSecurity", "mod_security", "NOYB"],
        ),
        (
            "AWS WAF",
            [("x-amzn-requestid", ""), ("x-amz-cf-id", "")],
            ["aws waf", "Request blocked"],
        ),
        (
            "Akamai",
            [("x-check-cacheable", ""), ("x-akamai-transformed", "")],
            ["akamai", "Reference&#32;#"],
        ),
        (
            "F5 BIG-IP ASM",
            [("x-cnection", ""), ("set-cookie", "TS0")],
            ["The requested URL was rejected", "F5"],
        ),
        (
            "Imperva / Incapsula",
            [("x-iinfo", ""), ("set-cookie", "incap_ses")],
            ["incapsula", "Request unsuccessful"],
        ),
        (
            "Sucuri",
            [("x-sucuri-id", ""), ("server", "sucuri")],
            ["sucuri", "Access Denied - Sucuri Website Firewall"],
        ),
        (
            "Barracuda",
            [("set-cookie", "barra_counter_session")],
            ["barracuda", "You have been blocked"],
        ),
        (
            "Wordfence",
            [],
            ["generated by wordfence", "wordfence"],
        ),
        (
            "Nginx WAF (generic)",
            [("server", "nginx")],
            ["nginx", "400 Bad Request"],
        ),
    ]

    PROBE_PAYLOADS = [
        "?test=<script>alert(1)</script>",
        "?id=1' OR '1'='1",
        "?file=../../../etc/passwd",
        "?cmd=cat+/etc/passwd",
    ]

    def __init__(
        self,
        session: Optional[requests.Session] = None,
        timeout: int = 10,
        proxies: Optional[Dict] = None,
    ):
        self.session = session or requests.Session()
        self.timeout = timeout
        self.proxies = proxies or {}
        self.session.verify = False

    # ------------------------------------------------------------------ #
    #  Public API                                                          #
    # ------------------------------------------------------------------ #

    def detect(self, url: str) -> WAFResult:
        """
        Run passive (header) detection then active (probe) detection.
        Returns a WAFResult with findings.
        """
        result = WAFResult()

        # 1. Baseline request
        try:
            base_resp = self.session.get(url, timeout=self.timeout,
                                         proxies=self.proxies)
        except requests.RequestException as e:
            result.recommendation = f"Could not reach target: {e}"
            return result

        # 2. Passive header fingerprinting
        passive = self._passive_detect(base_resp)
        if passive:
            result.detected = True
            result.name = passive[0]
            result.confidence = passive[1]
            result.indicators = passive[2]

        # 3. Active probe — send suspicious payloads
        for probe in self.PROBE_PAYLOADS:
            probe_url = url.rstrip("/") + probe
            try:
                resp = self.session.get(probe_url, timeout=self.timeout,
                                        proxies=self.proxies)
                active = self._active_detect(resp, base_resp)
                if active:
                    if not result.detected:
                        result.detected = True
                        result.name = active[0]
                        result.confidence = active[1]
                    result.indicators += active[2]
                    result.confidence = min(100, result.confidence + 15)
                    break
            except requests.RequestException:
                pass

        result.recommendation = self._build_recommendation(result)
        return result

    def quick_check(self, url: str) -> bool:
        """Fast boolean WAF check (headers only)."""
        try:
            resp = self.session.get(url, timeout=self.timeout, proxies=self.proxies)
            return bool(self._passive_detect(resp))
        except Exception:
            return False

    # ------------------------------------------------------------------ #
    #  Detection logic                                                     #
    # ------------------------------------------------------------------ #

    def _passive_detect(
        self, resp: requests.Response
    ) -> Optional[Tuple[str, int, List[str]]]:
        headers = {k.lower(): v.lower() for k, v in resp.headers.items()}
        body = resp.text.lower()

        for waf_name, header_sigs, body_sigs in self.SIGNATURES:
            indicators: List[str] = []
            confidence = 0

            for hkey, hval in header_sigs:
                if hkey in headers:
                    if hval == "" or hval in headers[hkey]:
                        indicators.append(f"Header: {hkey}")
                        confidence += 30

            for bsig in body_sigs:
                if bsig.lower() in body:
                    indicators.append(f"Body: {bsig}")
                    confidence += 25

            if confidence >= 30:
                return (waf_name, min(confidence, 100), indicators)

        return None

    def _active_detect(
        self,
        probe_resp: requests.Response,
        base_resp: requests.Response,
    ) -> Optional[Tuple[str, int, List[str]]]:
        """Compare probe response against baseline for WAF blocking patterns."""
        indicators: List[str] = []
        confidence = 0

        # Status code change from 200 → 403/406/429/503
        blocking_codes = {403, 406, 429, 503}
        if base_resp.status_code == 200 and probe_resp.status_code in blocking_codes:
            indicators.append(f"Status change: {base_resp.status_code} → {probe_resp.status_code}")
            confidence += 40

        # Body keywords common in WAF block pages
        block_phrases = [
            "blocked", "forbidden", "access denied", "security", "firewall",
            "illegal", "attack", "threat", "malicious",
        ]
        body = probe_resp.text.lower()
        for phrase in block_phrases:
            if phrase in body:
                indicators.append(f"Block phrase: '{phrase}'")
                confidence += 15
                break

        # Significant body size change (block page vs normal page)
        size_diff = abs(len(probe_resp.text) - len(base_resp.text))
        if size_diff > 500 and probe_resp.status_code != base_resp.status_code:
            indicators.append(f"Body size diff: {size_diff} bytes")
            confidence += 10

        if confidence >= 40:
            return ("Unknown WAF", min(confidence, 100), indicators)
        return None

    # ------------------------------------------------------------------ #
    #  Helpers                                                             #
    # ------------------------------------------------------------------ #

    @staticmethod
    def _build_recommendation(result: WAFResult) -> str:
        if not result.detected:
            return "No WAF detected — proceed with all bypass techniques."
        base = f"{result.name} detected (confidence {result.confidence}%). "
        tips = {
            "Cloudflare": "Try slow-rate sending, IP rotation, and encoded payloads.",
            "ModSecurity": "Use CRS bypass payloads; test chunked encoding and HPP.",
            "AWS WAF":     "Try URL encoding, JSON body payloads, and chunked requests.",
            "Akamai":      "Use header injection and encoding tricks.",
            "F5 BIG-IP ASM": "Try parameter pollution and encoding variations.",
            "Imperva / Incapsula": "Use slow HTTP, encoding, and session rotation.",
        }
        return base + tips.get(result.name, "Use encoded/obfuscated payloads and rate limiting.")
